"use client";

import { useState } from "react";
import type { AnalysisResult } from "@/lib/analyzer";
import { ReleaseVerification } from "@/components/release-verification";

type Tab = "overview" | "security" | "classes" | "build" | "source";
const TABS: Array<{ id: Tab; label: string }> = [{ id: "overview", label: "Overview" }, { id: "security", label: "Security" }, { id: "classes", label: "Classes" }, { id: "build", label: "Build" }, { id: "source", label: "Source" }];

export function Overview({ result, onReset }: { result: AnalysisResult; onReset: () => void }) {
  const [tab, setTab] = useState<Tab>("overview");
  const { metadata, archive, file, security, classes, build, source } = result;
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 font-mono text-sm text-emerald-300">✓ LOCAL ANALYSIS COMPLETE</p><h2 className="text-3xl font-semibold text-white">{metadata.name || file.name}</h2><p className="mt-2 text-sm text-slate-500">{file.name} · {formatBytes(file.size)} · {metadata.version ? `version ${metadata.version}` : "version unknown"}</p></div><div className="flex flex-wrap gap-2"><button onClick={() => exportReport(result)} className="rounded-lg bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-cyan-300">Export JSON report</button><button onClick={onReset} className="rounded-lg border border-slate-700 px-4 py-2 text-sm text-slate-300 hover:border-slate-500 hover:text-white">Inspect another JAR</button></div></div>

    <div className="grid gap-3 sm:grid-cols-3"><ScoreCard label="Security risk" value={`${security.score}/100`} detail={`${security.level} · ${security.findings.length} findings`} style={riskStyle(security.level)} /><ScoreCard label="Build integrity" value="Fingerprint ready" detail={`${build.tool} · ${shortHash(build.sha256)}`} style="border-cyan-900/70 bg-cyan-950/20 text-cyan-200" /><ScoreCard label="Source identity" value={source.repository ? "Repository found" : "Not detected"} detail={source.repository?.url || "Manual repository input available"} style={source.repository ? "border-emerald-900/70 bg-emerald-950/20 text-emerald-200" : "border-slate-800 bg-slate-900/60 text-slate-300"} /></div>

    <nav className="flex gap-1 overflow-x-auto rounded-xl border border-slate-800 bg-slate-900/70 p-1" aria-label="Analysis sections">{TABS.map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={`min-w-max flex-1 rounded-lg px-4 py-2.5 text-sm transition ${tab === item.id ? "bg-slate-700 text-white" : "text-slate-500 hover:bg-slate-800 hover:text-slate-300"}`}>{item.label}{item.id === "security" && security.findings.length > 0 ? ` (${security.findings.length})` : ""}</button>)}</nav>

    {tab === "overview" && <div className="space-y-5"><section className="grid gap-5 lg:grid-cols-3"><div className="rounded-xl border border-slate-800 bg-slate-900/70 p-5 lg:col-span-2"><SectionTitle eyebrow="PLUGIN DESCRIPTOR" title="Plugin metadata" badge={metadata.source || "descriptor missing"} /><div className="mt-3 grid gap-x-6 sm:grid-cols-2"><Row label="Name" value={metadata.name} /><Row label="Version" value={metadata.version} /><Row label="Main class" value={metadata.main} /><Row label="API version" value={metadata.apiVersion} /><Row label="Author(s)" value={metadata.authors?.join(", ")} /><Row label="Website" value={metadata.website} /><Row label="Load phase" value={metadata.load} /><Row label="Prefix" value={metadata.prefix} /></div>{metadata.description && <p className="mt-4 rounded-lg border border-slate-800 bg-slate-950/40 p-4 text-sm leading-6 text-slate-400">{metadata.description}</p>}</div><div className="rounded-xl border border-slate-800 bg-slate-900/70 p-5"><SectionTitle eyebrow="ARCHIVE" title="Contents" /><div className="mt-5 grid grid-cols-2 gap-4"><Metric value={archive.classCount} label="Classes" /><Metric value={archive.resourceCount} label="Resources" /><Metric value={archive.embeddedJarCount} label="Nested JARs" /><Metric value={archive.nativeLibraryCount} label="Native libs" /><Metric value={archive.serviceProviderCount} label="Services" /><Metric value={archive.signed ? "Yes" : "No"} label="Signed archive" /></div></div></section><section className="rounded-xl border border-slate-800 bg-slate-900/70 p-5"><SectionTitle eyebrow="PLUGIN SURFACE" title="Server integration" /><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><ListCard title="Required dependencies" values={metadata.requiredDependencies} /><ListCard title="Soft dependencies" values={metadata.softDependencies} /><ListCard title="Load before" values={metadata.loadBefore} /><ListCard title="Commands" values={metadata.commands} /><ListCard title="Permissions" values={metadata.permissions} /><ListCard title="Libraries" values={metadata.libraries} /></div></section></div>}

    {tab === "security" && <section className="rounded-xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><SectionTitle eyebrow="STATIC SECURITY" title="Capabilities & evidence" /><div className={`rounded-lg border px-3 py-2 text-right ${riskStyle(security.level)}`}><p className="font-mono text-2xl font-bold">{security.score}<span className="text-sm">/100</span></p><p className="text-xs uppercase tracking-wider">{security.level} risk</p></div></div><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-500">Capabilities are review evidence, not proof of malicious intent. Exact method calls are scored only when they belong to the plugin package; bundled dependency signals stay informational.</p>{security.findings.length ? <div className="mt-5 grid gap-3 lg:grid-cols-2">{security.findings.map((finding) => <div key={finding.id} className="rounded-lg border border-slate-800 bg-slate-950/50 p-4"><div className="flex items-start justify-between gap-3"><div><div className="mb-2 flex flex-wrap gap-1.5"><span className={`inline-block rounded px-2 py-0.5 text-[10px] uppercase tracking-wider ${finding.severity === "high" ? "bg-rose-400/10 text-rose-300" : finding.severity === "medium" ? "bg-amber-400/10 text-amber-300" : "bg-slate-800 text-slate-400"}`}>{finding.severity}</span><span className="inline-block rounded bg-cyan-400/10 px-2 py-0.5 text-[10px] uppercase tracking-wider text-cyan-300">{finding.scope === "plugin" ? "plugin code" : finding.scope === "dependency" ? "bundled dependency" : "archive"}</span></div><p className="font-medium text-slate-200">{finding.title}</p></div><div className="text-right"><span className="block font-mono text-xs text-slate-500">{finding.occurrences} refs</span><span className={`mt-1 block font-mono text-[10px] ${finding.scoreImpact ? "text-amber-300" : "text-emerald-400"}`}>{finding.scoreImpact ? `+${finding.scoreImpact} risk` : "informational"}</span></div></div><p className="mt-2 text-xs leading-5 text-slate-500">{finding.description}</p>{finding.locations.length > 0 && <div className="mt-3 space-y-1 border-t border-slate-800 pt-3">{finding.locations.map((location) => <p key={location} className="break-all font-mono text-[11px] leading-5 text-cyan-300/80">{location}</p>)}</div>}</div>)}</div> : <div className="mt-5 rounded-lg border border-emerald-900/50 bg-emerald-950/20 p-4 text-sm text-emerald-200">No configured capability signals were found in {security.scannedClasses} parsed classes.</div>}</section>}

    {tab === "classes" && <section className="rounded-xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><SectionTitle eyebrow="JVM INVENTORY" title="Classes & method calls" /><p className="font-mono text-sm text-slate-400">{classes.classCount} classes · {classes.methodCount} methods · {classes.callCount} calls · Java {classes.javaVersions.join(", ") || "unknown"}</p></div><div className="mt-5 grid gap-3 md:grid-cols-2">{classes.classes.map((item) => <div key={item.path} className="rounded-lg border border-slate-800 bg-slate-950/50 p-4"><p className="break-all font-mono text-xs text-cyan-300">{item.name}</p><p className="mt-2 text-xs text-slate-500">Class format {item.javaVersion} · {item.methods.length} methods · {item.callCount} decoded calls</p><div className="mt-3 space-y-1">{item.methods.slice(0, 5).map((method) => <p key={method} className="truncate font-mono text-[11px] text-slate-600">{method}</p>)}</div></div>)}</div>{classes.classCount > classes.classes.length && <p className="mt-4 text-xs text-slate-500">Showing the first {classes.classes.length} classes in the interactive overview. The exported report includes aggregate counts.</p>}</section>}

    {tab === "build" && <section className="rounded-xl border border-slate-800 bg-slate-900/70 p-5"><SectionTitle eyebrow="BUILD IDENTITY" title="Build & binary evidence" badge={build.tool === "Unknown" ? "build tool unknown" : `${build.tool} detected`} /><div className="mt-5 rounded-lg border border-slate-800 bg-slate-950/50 p-4"><p className="text-xs text-slate-500">SHA-256 fingerprint</p><p className="mt-2 break-all font-mono text-xs leading-5 text-cyan-200">{build.sha256}</p></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><BuildField label="Declared plugin version" value={build.declaredVersion} source="plugin descriptor" /><BuildField label="Embedded build version" value={build.implementationVersion} source={build.versionSource} /><BuildField label="Artifact coordinate" value={[build.group, build.artifact].filter(Boolean).join(":")} /><BuildField label="Title / module" value={build.title || build.automaticModuleName} /><BuildField label="Git commit" value={build.commit} /><BuildField label="Build JDK" value={build.buildJdk} /><BuildField label="Created by" value={build.createdBy} /><BuildField label="Built by" value={build.builtBy} /><BuildField label="Vendor" value={build.implementationVendor} /><BuildField label="Language signals" value={build.languageSignals.join(", ")} /><BuildField label="Build-tool evidence" value={build.toolEvidence.join(", ")} /><BuildField label="Metadata sources" value={build.sources.join(", ")} /></div>{build.tool === "Unknown" && <p className="mt-4 rounded-lg border border-amber-900/50 bg-amber-950/20 px-4 py-3 text-xs leading-5 text-amber-200">No reliable Gradle or Maven marker was embedded. PluginLens does not invent missing build metadata.</p>}</section>}

    {tab === "source" && <ReleaseVerification source={source} build={build} />}
  </div>;
}

const Row = ({ label, value }: { label: string; value?: string }) => <div className="flex items-start justify-between gap-6 border-b border-slate-800 py-3"><span className="text-sm text-slate-500">{label}</span><span className="break-all text-right font-mono text-sm text-slate-200">{value || "—"}</span></div>;
function SectionTitle({ eyebrow, title, badge }: { eyebrow: string; title: string; badge?: string }) { return <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-xs text-slate-500">{eyebrow}</p><h3 className="mt-1 text-lg font-medium text-white">{title}</h3></div>{badge && <span className="rounded-full bg-cyan-400/10 px-2.5 py-1 text-xs text-cyan-300">{badge}</span>}</div>; }
function ScoreCard({ label, value, detail, style }: { label: string; value: string; detail: string; style: string }) { return <div className={`min-w-0 rounded-xl border p-4 ${style}`}><p className="text-xs opacity-70">{label}</p><p className="mt-2 text-lg font-semibold">{value}</p><p className="mt-1 truncate text-xs opacity-60">{detail}</p></div>; }
function Metric({ value, label }: { value: number | string; label: string }) { return <div><p className="font-mono text-xl font-semibold text-slate-100">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>; }
function ListCard({ title, values }: { title: string; values: string[] }) { return <div className="rounded-lg border border-slate-800 bg-slate-950/40 p-4"><p className="text-xs text-slate-500">{title}</p><p className={`mt-2 break-words font-mono text-xs leading-5 ${values.length ? "text-slate-300" : "text-slate-600"}`}>{values.length ? values.join(", ") : "None declared"}</p></div>; }
function BuildField({ label, value, source }: { label: string; value?: string; source?: string }) { return <div className="min-w-0 rounded-lg border border-slate-800 bg-slate-950/40 p-4"><p className="text-xs text-slate-500">{label}</p><p className={`mt-2 break-all font-mono text-xs leading-5 ${value ? "text-slate-200" : "text-slate-600"}`}>{value || "Not embedded in JAR"}</p>{value && source && <p className="mt-2 truncate text-[10px] text-slate-600">source: {source}</p>}</div>; }
function formatBytes(bytes: number) { return bytes >= 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(2)} MB` : `${(bytes / 1024).toFixed(1)} KB`; }
function shortHash(hash: string) { return `${hash.slice(0, 8)}…${hash.slice(-8)}`; }
function exportReport(result: AnalysisResult) { const payload = JSON.stringify(result, null, 2); const url = URL.createObjectURL(new Blob([payload], { type: "application/json" })); const anchor = document.createElement("a"); const base = (result.metadata.name || result.file.name.replace(/\.jar$/i, "plugin")).replace(/[^a-z0-9._-]+/gi, "-"); anchor.href = url; anchor.download = `${base}-pluginlens-report.json`; anchor.click(); URL.revokeObjectURL(url); }
function riskStyle(level: "low" | "medium" | "high" | "critical") { return ({ low: "border-emerald-900 bg-emerald-950/30 text-emerald-300", medium: "border-amber-900 bg-amber-950/30 text-amber-300", high: "border-orange-900 bg-orange-950/30 text-orange-300", critical: "border-rose-900 bg-rose-950/30 text-rose-300" })[level]; }
