import type { AnalysisResult } from "@/lib/analyzer";

const Row = ({ label, value }: { label: string; value?: string }) => <div className="flex items-start justify-between gap-6 border-b border-slate-800 py-3 last:border-0"><span className="text-sm text-slate-500">{label}</span><span className="break-all text-right font-mono text-sm text-slate-200">{value || "—"}</span></div>;

export function Overview({ result, onReset }: { result: AnalysisResult; onReset: () => void }) {
  const { metadata, archive, file, security, classes, build } = result;
  return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 font-mono text-sm text-emerald-300">✓ LOCAL ANALYSIS COMPLETE</p><h2 className="text-3xl font-semibold text-white">{metadata.name || file.name}</h2><p className="mt-2 text-sm text-slate-500">{file.name} · {(file.size / 1024).toFixed(1)} KB</p></div><button onClick={onReset} className="rounded-lg border border-slate-700 px-4 py-2 text-sm text-slate-300 hover:border-slate-500 hover:text-white">Inspect another JAR</button></div>
    <div className="grid gap-5 lg:grid-cols-3"><section className="rounded-xl border border-slate-800 bg-slate-900/70 p-5 lg:col-span-2"><div className="mb-4 flex items-center justify-between"><h3 className="font-medium text-white">Plugin overview</h3><span className={`rounded-full px-2.5 py-1 text-xs ${metadata.source === "plugin.yml" ? "bg-cyan-400/10 text-cyan-300" : "bg-amber-400/10 text-amber-300"}`}>{metadata.source || "Manifest missing"}</span></div><Row label="Name" value={metadata.name} /><Row label="Version" value={metadata.version} /><Row label="Main class" value={metadata.main} /><Row label="API version" value={metadata.apiVersion} /><Row label="Author(s)" value={metadata.authors?.join(", ")} /><Row label="Website" value={metadata.website} /></section>
      <aside className="rounded-xl border border-slate-800 bg-slate-900/70 p-5"><h3 className="font-medium text-white">Archive signal</h3><div className="mt-5 space-y-4"><div><p className="text-3xl font-semibold text-cyan-300">{archive.classCount}</p><p className="text-xs text-slate-500">Compiled classes</p></div><div><p className="text-3xl font-semibold text-slate-100">{archive.entryCount}</p><p className="text-xs text-slate-500">Archive entries</p></div><div><p className="text-3xl font-semibold text-slate-100">{archive.resourceCount}</p><p className="text-xs text-slate-500">Resources</p></div></div></aside></div>
    <section className="rounded-xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-xs text-slate-500">LOCAL SECURITY SCAN</p><h3 className="mt-1 text-lg font-medium text-white">Capability signals</h3></div><div className={`rounded-lg border px-3 py-2 text-right ${riskStyle(security.level)}`}><p className="font-mono text-2xl font-bold">{security.score}<span className="text-sm">/100</span></p><p className="text-xs uppercase tracking-wider">{security.level} risk</p></div></div><p className="mt-3 text-sm leading-6 text-slate-500">This is a static capability scan, not a verdict. A match means code references an API that deserves review.</p>{security.findings.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{security.findings.map((finding) => <div key={finding.id} className="rounded-lg border border-slate-800 bg-slate-950/50 p-4"><div className="flex justify-between gap-3"><p className="font-medium text-slate-200">{finding.title}</p><span className="font-mono text-xs text-slate-500">{finding.occurrences} refs</span></div><p className="mt-1 text-xs leading-5 text-slate-500">{finding.description}</p>{finding.locations.length > 0 && <p className="mt-3 break-all font-mono text-[11px] leading-5 text-cyan-300/80">in {finding.locations.join(", ")}</p>}</div>)}</div> : <div className="mt-5 rounded-lg border border-emerald-900/50 bg-emerald-950/20 p-4 text-sm text-emerald-200">No initial capability signals were found in {security.scannedClasses} compiled classes.</div>}</section>
    <section className="rounded-xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-xs text-slate-500">CLASS INVENTORY</p><h3 className="mt-1 text-lg font-medium text-white">JVM structure</h3></div><p className="font-mono text-sm text-slate-400">{classes.classCount} classes · {classes.methodCount} methods · Java {classes.javaVersions.join(", ") || "unknown"}</p></div>{classes.classes.length > 0 && <div className="mt-5 grid gap-3 md:grid-cols-2">{classes.classes.map((item) => <div key={item.path} className="rounded-lg border border-slate-800 bg-slate-950/50 p-4"><p className="break-all font-mono text-xs text-cyan-300">{item.name}</p><p className="mt-2 text-xs text-slate-500">Java class format {item.javaVersion} · {item.methods.length} methods</p><p className="mt-2 truncate font-mono text-[11px] text-slate-600">{item.methods.slice(0, 3).join(" · ") || "No declared methods"}</p></div>)}</div>}</section>
    <section className="rounded-xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-xs text-slate-500">BUILD IDENTITY</p><h3 className="mt-1 text-lg font-medium text-white">Build & binary evidence</h3></div><div className="flex gap-2"><span className={`rounded-full px-2.5 py-1 text-xs ${build.tool === "Unknown" ? "bg-slate-800 text-slate-400" : "bg-violet-400/10 text-violet-300"}`}>{build.tool === "Unknown" ? "build tool unknown" : `${build.tool} detected`}</span><span className="rounded-full bg-cyan-400/10 px-2.5 py-1 text-xs text-cyan-300">local only</span></div></div><div className="mt-5 rounded-lg border border-slate-800 bg-slate-950/50 p-4"><p className="text-xs text-slate-500">SHA-256 fingerprint</p><p className="mt-2 break-all font-mono text-xs leading-5 text-cyan-200">{build.sha256}</p></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><BuildField label="Declared plugin version" value={build.declaredVersion} source="plugin.yml / paper-plugin.yml" /><BuildField label="Embedded build version" value={build.implementationVersion} source={build.versionSource} /><BuildField label="Artifact coordinate" value={[build.group, build.artifact].filter(Boolean).join(":")} /><BuildField label="Title / module" value={build.title || build.automaticModuleName} /><BuildField label="Git commit" value={build.commit} /><BuildField label="Build JDK" value={build.buildJdk} /><BuildField label="Created by" value={build.createdBy} /><BuildField label="Built by" value={build.builtBy} /><BuildField label="Vendor" value={build.implementationVendor} /><BuildField label="Language signals" value={build.languageSignals.join(", ")} /><BuildField label="Build-tool evidence" value={build.toolEvidence.join(", ")} /><BuildField label="Metadata sources" value={build.sources.join(", ")} /></div>{build.tool === "Unknown" && <p className="mt-4 rounded-lg border border-amber-900/50 bg-amber-950/20 px-4 py-3 text-xs leading-5 text-amber-200">No reliable Gradle or Maven marker was embedded in this JAR. Gradle builds often omit build metadata unless the project writes it into the manifest or a properties file; PluginLens will not invent a build tool from missing evidence.</p>}<p className="mt-4 text-xs leading-5 text-slate-500">Ready for official release hash comparison. The JAR and fingerprint remain on this device.</p></section>
    <section className="rounded-xl border border-slate-800 bg-slate-900/40 p-5"><p className="font-mono text-xs text-slate-500">NEXT MODULES</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><Module title="Method call tracing" text="Map calls to specific methods." /><Module title="Official binary match" text="Compare this SHA-256 with a release." /><Module title="Source verification" text="Repository/tag relationship." /></div></section>
  </div>;
}
function Module({ title, text }: { title: string; text: string }) { return <div className="rounded-lg border border-slate-800 bg-slate-950/50 p-4"><p className="text-sm font-medium text-slate-300">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p><p className="mt-3 font-mono text-xs text-slate-600">planned</p></div>; }
function BuildField({ label, value, source }: { label: string; value?: string; source?: string }) { return <div className="min-w-0 rounded-lg border border-slate-800 bg-slate-950/40 p-4"><p className="text-xs text-slate-500">{label}</p><p className={`mt-2 break-all font-mono text-xs leading-5 ${value ? "text-slate-200" : "text-slate-600"}`}>{value || "Not embedded in JAR"}</p>{value && source && <p className="mt-2 truncate text-[10px] text-slate-600">source: {source}</p>}</div>; }
function riskStyle(level: "low" | "medium" | "high" | "critical") { return ({ low: "border-emerald-900 bg-emerald-950/30 text-emerald-300", medium: "border-amber-900 bg-amber-950/30 text-amber-300", high: "border-orange-900 bg-orange-950/30 text-orange-300", critical: "border-rose-900 bg-rose-950/30 text-rose-300" })[level]; }
