import type { AnalysisResult } from "@/lib/analyzer";

const Row = ({ label, value }: { label: string; value?: string }) => <div className="flex items-start justify-between gap-6 border-b border-slate-800 py-3 last:border-0"><span className="text-sm text-slate-500">{label}</span><span className="break-all text-right font-mono text-sm text-slate-200">{value || "—"}</span></div>;

export function Overview({ result, onReset }: { result: AnalysisResult; onReset: () => void }) {
  const { metadata, archive, file } = result;
  return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 font-mono text-sm text-emerald-300">✓ LOCAL ANALYSIS COMPLETE</p><h2 className="text-3xl font-semibold text-white">{metadata.name || file.name}</h2><p className="mt-2 text-sm text-slate-500">{file.name} · {(file.size / 1024).toFixed(1)} KB</p></div><button onClick={onReset} className="rounded-lg border border-slate-700 px-4 py-2 text-sm text-slate-300 hover:border-slate-500 hover:text-white">Inspect another JAR</button></div>
    <div className="grid gap-5 lg:grid-cols-3"><section className="rounded-xl border border-slate-800 bg-slate-900/70 p-5 lg:col-span-2"><div className="mb-4 flex items-center justify-between"><h3 className="font-medium text-white">Plugin overview</h3><span className={`rounded-full px-2.5 py-1 text-xs ${metadata.source === "plugin.yml" ? "bg-cyan-400/10 text-cyan-300" : "bg-amber-400/10 text-amber-300"}`}>{metadata.source || "Manifest missing"}</span></div><Row label="Name" value={metadata.name} /><Row label="Version" value={metadata.version} /><Row label="Main class" value={metadata.main} /><Row label="API version" value={metadata.apiVersion} /><Row label="Author(s)" value={metadata.authors?.join(", ")} /><Row label="Website" value={metadata.website} /></section>
      <aside className="rounded-xl border border-slate-800 bg-slate-900/70 p-5"><h3 className="font-medium text-white">Archive signal</h3><div className="mt-5 space-y-4"><div><p className="text-3xl font-semibold text-cyan-300">{archive.classCount}</p><p className="text-xs text-slate-500">Compiled classes</p></div><div><p className="text-3xl font-semibold text-slate-100">{archive.entryCount}</p><p className="text-xs text-slate-500">Archive entries</p></div><div><p className="text-3xl font-semibold text-slate-100">{archive.resourceCount}</p><p className="text-xs text-slate-500">Resources</p></div></div></aside></div>
    <section className="rounded-xl border border-slate-800 bg-slate-900/40 p-5"><p className="font-mono text-xs text-slate-500">NEXT MODULES</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><Module title="Security scanner" text="Behavioural findings and indicators." /><Module title="Class parser" text="Bytecode-aware inspection." /><Module title="Build verification" text="Official release matching." /></div></section>
  </div>;
}
function Module({ title, text }: { title: string; text: string }) { return <div className="rounded-lg border border-slate-800 bg-slate-950/50 p-4"><p className="text-sm font-medium text-slate-300">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p><p className="mt-3 font-mono text-xs text-slate-600">planned</p></div>; }
